### ISSUE TITLE
Unable to make it work with Express4

### ISSUE THREAD

**Issue by sylbal** [yahoo/express-state#37]
Hi,
Not sure if I should post here or in StackOverflow for my question. I'm quite new to Node and I can't make express-state working with express4. My attached sample is quite close to your "basic example" and after few hours I'm still puzzled with that.

Here's my server code:
```javascript
var express = require('express');
var app = express();
var server = require('http').Server(app);
var state = require('express-state');

state.extend(app);

var config = {
    key1: "val1",
    key2: "val2"
};

app.expose(config, 'myConfig');

// Start the server.
server.listen(process.env.NODE_PORT || 5000, function(){
    console.log("Express server listening on port " + server.address().port);
});

app.get('/', function (req, res) {
    res.expose('John', 'name');

    res.send(
        '<html>' +
        '<h1>test express</h1>' +
        '<script>' +
        'console.log("hello");' +
        'console.log(name);' +
        'console.log(myConfig);' +
        '</script>' +
        '</html>'
    );
});
```
In the console, name returns an empty string and myConfig throws an "Reference error : not defined". What did I missed ? 
Any help welcome

**Comment by caridy** [comment]
you have to output `res.locals.state`, which is a blob of javascript, in your page, like this:

```
...
app.get('/', function (req, res) {
    res.expose('John', 'name');

    res.send(
        '<html>' +
        '<h1>test express</h1>' +
        '<script>' +
        res.locals.state +
        '</script>' +
        '<script>' +
        'console.log("hello");' +
        'console.log(name);' +
        'console.log(myConfig);' +
        '</script>' +
        '</html>'
    );
});
```

more details here: https://github.com/yahoo/express-state#serialization

**Comment by sylbal** [comment]
Thank you for your help, works now. I should be able to transpose to my app using Jade.

**Comment by caridy** [comment]
@ericf @jconniff maybe we should add an explicit note into the README about this.
